spring.application.name=smart
spring.datasource.url=jdbc:mysql://localhost:3306/smartdb
spring.datasource.username=root
spring.datasource.password=senai

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=8088

api.estoque-api-url=http://localhost:8088/estoque
api.expedicao-api-url=http://localhost:8088/expedicao
api.seletor-tampas-present=true
